### ISSUE TITLE
Kamehameha API

### ISSUE THREAD

**Issue by rednaks** [moztn/moztn.github.com#3]
We are using the public, un-registred GithubAPI, but it's very limited (number of requests) and requires many connections from the client side, the result is very slow page loading and the limitation can be reached quickly.

So the Idea is to create a kind of ProxyAPI, that will gather the wanted data on our servers and "push" it only once to the clients. like the kamehameha :D

**Comment by raed667** [comment]
I know that in some APIs (like 4sq) that violates the terms and conditions (tried to do that :wink: ). So if this is for a "formal" project check the terms before.

**Comment by rednaks** [comment]
IDK, they talk about excessive API usage, if this will violated the terms and condition we can always try to cache the data and update it each 1min decrease the access.

**Comment by raed667** [comment]
IDK either just a heads up ;)

**Comment by raed667** [comment]
GET http://vps.mozilla-tunisia.org:5000/ net::ERR_CONNECTION_RESET

**Comment by rednaks** [comment]
Yes, it's because of the mixed content :( (HTTPS/HTTP) I though github.io was http ... and a self signed cert wont fix that.
This should be fixed as soon as we use a domain name instead of moztn.github.io

**Comment by rednaks** [comment]
Now it's fixed :) we should wait for DNS http://github.mozilla-tunisia.org/
